on: [push]

jobs:
  unit_test_job:
    runs-on: ubuntu-latest
    name: Unit Testing
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unit test
        id: unit_test
        uses: quantifex/rust_oregontrail_1978@111b483cc68001997e2186d59d6e5e39b4ccfcd9
      - name: Archive code coverage
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_coverage
          path: coverage/
